IMAGE:
  WIDTH: 640
  HEIGHT: 480
  Y_OFFSET: 440
  # find your ROI parameter.


CALIBRATE:
  fx: 353.8469384729813
  fy: 351.4667826997972
  cx: 310.2594404751567
  cy: 249.2598353257313

  k1: 0.316783915735281
  k2: 0.316783915735281
  p1: 0.001388654435807697
  p2: -0.002171949748410683
  k3: 0

XYCAR:
  START_SPEED: 8.0
  MAX_SPEED: 14.0
  MIN_SPEED: 5.0
  SPEED_CONTROL_THRESHOLD: 20.0
  ACCELERATION_STEP: 0.7
  DECELERATION_STEP: 0.8
  # find your parameter.

# If you want to use other control methods, Change PID to another control methods.
PID:
  P_GAIN: 0.15
  I_GAIN: 0.0000
  D_GAIN: 0.06
  P_GAIN_CURVE: 0.7
  I_GAIN_CURVE: 0.0000
  D_GAIN_CURVE: 0.00
  # find your parameter.

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 20

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true
